export const subjectFilters = [
  { label: 'All Subjects', count: 1280, active: true },
  { label: 'Mathematics', count: 320 },
  { label: 'Science', count: 280 },
  { label: 'Languages', count: 210 },
  { label: 'Computer Science', count: 180 },
  { label: 'Business', count: 140 },
  { label: 'Humanities', count: 150 },
];

export const languageFilters = [
  { label: 'All Languages', active: true },
  { label: 'English' },
  { label: 'Spanish' },
  { label: 'French' },
  { label: 'Arabic' },
];

export const difficultyFilters = ['All Levels', 'Beginner', 'Intermediate', 'Advanced'];

export const typeFilters = ['All Types', 'Video', 'Written', 'Interactive'];

export const resources = [
  {
    id: 1,
    title: 'Quadratic Equations Explained Simply',
    description: 'Step-by-step solution with real examples.',
    category: 'Mathematics',
    author: 'Alex M.',
    rating: 4.9,
    views: '2.1K',
    likes: 356,
    duration: '12:45',
    thumb: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=12',
    color: '#2563EB',
  },
  {
    id: 2,
    title: 'Chemical Reactions Made Easy',
    description: 'Understand chemistry with fun examples.',
    category: 'Science',
    author: 'Rohan K.',
    rating: 4.8,
    views: '1.8K',
    likes: 278,
    duration: '15:30',
    thumb: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=15',
    color: '#0891B2',
  },
  {
    id: 3,
    title: 'English Grammar Tips You Need to Know',
    description: 'Improve your writing and speaking skills.',
    category: 'Languages',
    author: 'Sara L.',
    rating: 4.9,
    views: '3.2K',
    likes: 412,
    duration: '8:22',
    thumb: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=33',
    color: '#7C3AED',
  },
  {
    id: 4,
    title: 'Photosynthesis Full Explanation',
    description: 'Detailed notes plus diagram and animations.',
    category: 'Biology',
    author: 'Neha P.',
    rating: 4.7,
    views: '1.2K',
    likes: 189,
    duration: '10:15',
    thumb: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=41',
    color: '#16A34A',
  },
  {
    id: 5,
    title: 'Basic Integration Tutorial',
    description: 'Easy explanation with practice problems.',
    category: 'Mathematics',
    author: 'David S.',
    rating: 4.8,
    views: '1.6K',
    likes: 231,
    duration: '9:18',
    thumb: 'https://images.unsplash.com/photo-1553484771-cc0d9b8c2b33?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=52',
    color: '#2563EB',
  },
  {
    id: 6,
    title: 'How to Study Smart Not Hard',
    description: 'Study tips that actually work.',
    category: 'Study Skills',
    author: 'Maya A.',
    rating: 4.9,
    views: '2.7K',
    likes: 503,
    duration: '7:45',
    thumb: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    avatar: 'https://i.pravatar.cc/100?img=5',
    color: '#9333EA',
  },
];
